import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import 'flag-icon-css/css/flag-icons.min.css';
import Image from "next/image";
import faceImage from "../public/paramont_image.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isEnglish, setEnglish] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Paramont Hernandez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className= "min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <ul className="flex items-centered">
              <li>
                <h1 className="text-xl font-burtons">ParamontHdz</h1>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" 
                  href="#">
                    {isEnglish ? 'Resume' : 'Currículum'}
                </a>
              </li>
            </ul>
            <ul className="flex items-centered">
            <li>
                <button onClick={() => setEnglish(!isEnglish)} className="px-6 border-none text-2xl">
                  {
                  isEnglish ? 
                  <span className="flag-icon flag-icon-us" title="Change to Spanish"></span> : 
                  <span className="flag-icon flag-icon-mx" title="Cambiar a inglés"></span>
                  }
                </button>
              </li>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" title={isEnglish ? 'Dark Mode' : 'Modo Oscuro'}/>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              {isEnglish ? 'Paramont Hernandez' : 'Paramont Hernández'}
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              {isEnglish ? 'Developer' : 'Desarrollador'}
            </h3>
            <a className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            {isEnglish ?
            <p>
              Software developer. Working to become a better version of myself.<br/>
              I love the world of software development and I always try to learn new things to keep up with the current trends and technologies.
            </p> :
            <p>
              Desarrollador de software. Trabajando para ser una mejor versión de mí mismo.<br/>
              Amo el mundo del desarrollo de software y siempre intento aprender nuevas cosas para mantenerme al corriente con las últimas tendencias en tecnología.
            </p>
            }
            </a>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href='https://www.linkedin.com/in/paramont-hernandez/'>
              <AiFillLinkedin/>
            </a>
            <a href='https://github.com/ParamontHdzGlz'>
            <AiFillGithub/>
            </a>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={faceImage} fill alt="" style={{objectFit:"cover"}}/>
          </div>
        </section>

      </main>
    </div>
  )
}
