import { useState } from "react";
import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub
} from "react-icons/ai";
import 'flag-icon-css/css/flag-icons.min.css';
import Image from "next/image";

import image_face from "../public/images/paramont_image.png";
import image_rankingApp from "../public/images/rankingApp.png";
import image_grind75 from "../public/images/grind75.png";
import image_pokemonAPI from "../public/images/pokemon_table.png";
import image_reactivities from "../public/images/Reactivities.png";
import image_diplomadoCdD from "../public/images/diplomadoCdD.png";
import image_clasificadorVoz from "../public/images/espectrogramaVoz.png";
import image_pieShop from "../public/images/pieShop.png";
import image_courseLib from "../public/images/courseLibrary.png";


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  const [isEnglish, setEnglish] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Paramont Hernandez</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className= "min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <ul className="flex items-centered">
              <li>
                <h1 className="text-xl font-burtons">ParamontHdz</h1>
              </li>
              <li>
                <a className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8" 
                  href="/paramontHdzGlz/Paramont_Hernandez_CV.pdf">
                    {isEnglish ? 'Resume' : 'Currículum'}
                </a>
              </li>
            </ul>
            <ul className="flex items-centered">
            <li>
                <button onClick={() => setEnglish(!isEnglish)} className="px-6 border-none text-2xl">
                  {
                  isEnglish ? 
                  <span className="flag-icon flag-icon-us" title="Change to Spanish"></span> : 
                  <span className="flag-icon flag-icon-mx" title="Cambiar a inglés"></span>
                  }
                </button>
              </li>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className="cursor-pointer text-2xl" title={isEnglish ? 'Dark Mode' : 'Modo Oscuro'}/>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              {isEnglish ? 'Paramont Hernandez' : 'Paramont Hernández'}
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              {isEnglish ? 'Developer' : 'Desarrollador'}
            </h3>
            <a className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            {isEnglish ?
            <p>
              Software developer. Working to become a better version of myself.<br/>
              I love the world of software development and I always try to learn new things to keep up with the current trends and technologies.
            </p> :
            <p>
              Desarrollador de software. Trabajando para ser una mejor versión de mí mismo.<br/>
              Amo el mundo del desarrollo de software y siempre intento aprender nuevas cosas para mantenerme al corriente con las últimas tendencias en tecnología.
            </p>
            }
            </a>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
            <a href='https://www.linkedin.com/in/paramont-hernandez/'>
              <AiFillLinkedin/>
            </a>
            <a href='https://github.com/ParamontHdzGlz'>
            <AiFillGithub/>
            </a>
          </div>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
            <Image src={image_face} fill alt="" style={{objectFit:"cover"}}/>
          </div>

          <div className="text-center mt-20 mb-5">
            <h3 className="text-3xl py-1 dark:text-white ">
              {isEnglish ?
                "Some of my projects" :
                "Algunos de mis proyectos"
              }
            </h3>
          </div>

          <div className="container mx-auto justify-center">

          <a href="https://github.com/ParamontHdzGlz/Reactivities" className="block">
              <div className="box text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
                <Image src={image_reactivities} alt="" height={150} className="mx-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">
                  Reactivities (in process)
                </h3>
                <p className="py-2 dark:text-gray-400">
                  {isEnglish ?
                    "Social network mockup-up implementing clean architecture with mediator pattern. Using ASP.NET and React.js." :
                    "Borrador para una red social que implementa clean architecture y el patrón de mediador. Usando ASP.NET y React.js."
                  }
                </p>
                <h4 className="pt-4 text-teal-600">#CleanArchitecture #mediator pattern #React.js #ASP.NET</h4>
              </div>
            </a>

            <a href="https://github.com/ParamontHdzGlz/BethanysPieShop" className="block">
              <div className="box text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
                <Image src={image_pieShop} alt="" height={150} className="mx-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">
                  Bethany's Pie Shop
                </h3>
                <p className="py-2 dark:text-gray-400">
                  {isEnglish ?
                    "Marketplace for a pie shop. Using ASP.NET Core with view support and .NET's Razor Pages." :
                    "Marketplace para una tienda de pays. Usando ASP.NET Core con soporte para views de Razor Pages."
                  }
                </p>
                <h4 className="pt-4 text-teal-600">#ASP.NET #Views #RazorPages #C# #MVC</h4>
              </div>
            </a>

            <a href="https://github.com/ParamontHdzGlz/RankingApp" className="block">
              <div className="box text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
                <Image src={image_rankingApp} alt="" height={150} className="mx-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">
                  Ranking App
                </h3>
                <p className="py-2 dark:text-gray-400">
                  {isEnglish ?
                    "Web application using ASP.NET Core and React.js to create interactive UI for ranking images." :
                    "Aplicación web que usa ASP.NET Core y React.js para crear una UI interactiva para clasificar imágenes."
                  }
                </p>
                <h4 className="pt-4 text-teal-600">#React.js #ASP.NET #javascript #HTML #CSS #C#</h4>
              </div>
            </a>

            <a href="https://github.com/ParamontHdzGlz/CourseLibrary" className="block">
              <div className="box text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
                <Image src={image_courseLib} alt="" height={150} className="mx-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">
                  Course Library
                </h3>
                <p className="py-2 dark:text-gray-400">
                  {isEnglish ?
                    "ASP.NET API project, going deeper into RESTful." :
                    "Projecto de API de ASP.NET, profundizando en REST."
                  }
                </p>
                <h4 className="pt-4 text-teal-600">#REST #ASP.NET #API #C# </h4>
              </div>
            </a>

            <a href="https://github.com/ParamontHdzGlz/Grind75" className="block">
              <div className="box text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
                <Image src={image_grind75} alt="" height={150} className="mx-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">
                  Grind75 problems
                </h3>
                <p className="py-2 dark:text-gray-400">
                  {isEnglish ?
                    "Competitive programing challenges from Gind75 solved." :
                    "Problemas resueltos de programación comptetitiva de Grind75."
                  }
                </p><br />
                <h4 className="pt-4 text-teal-600">#CompetitivePrograming #ProblemSolving #Algorithms #DataStrcutures</h4>
              </div>
            </a>

            <a href="https://github.com/ParamontHdzGlz/Diplomado-CienciaDeDatos-Modulo1" className="block">
              <div className="box text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
                <Image src={image_diplomadoCdD} alt="" height={150} className="mx-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">
                  {isEnglish ?
                    "Data Science Diploma" :
                    "Diplomado de Ciencia de Datos"
                  }
                </h3>
                <p className="py-2 dark:text-gray-400">
                  {isEnglish ?
                    "Activities from the Data Science diploma I took, taught by the UNAM." :
                    "Actividades realizadas para el diplomado de ciencia de datos impartido por la UNAM."
                  }
                </p>
                <h4 className="pt-4 text-teal-600">#CienciaDeDatos #python #Pandas #Plotly #Scikit-learn #Keras #TensorFlow</h4>
              </div>
            </a>

            <a href="https://github.com/ParamontHdzGlz/Diplomado-CienciaDeDatos-Modulo4/blob/main/proyecto/proyecto-hernandez-gonzalez-paramont.ipynb" className="block">
              <div className="box text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
                <Image src={image_clasificadorVoz} alt="" height={150} className="mx-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">
                  {isEnglish ?
                    "Voice classifier" :
                    "Clasificador de voz"
                  }
                </h3>
                <p className="py-2 dark:text-gray-400">
                  {isEnglish ?
                    "Voice file classifier depending on sex." :
                    "Clasificador archivos de voz por sexo."
                  }
                </p>
                <h4 className="pt-4 text-teal-600">#python #Pandas #Numpy #Keras #Espectrograma</h4>
              </div>
            </a>

            <a href="https://github.com/ParamontHdzGlz/pokeAPI" className="block">
              <div className="box text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-800 flex-1">
                <Image src={image_pokemonAPI} alt="" height={150} className="mx-auto" />
                <h3 className="text-lg font-medium pt-8 pb-2 dark:text-gray-400">
                  Pokemon API
                </h3>
                <p className="py-2 dark:text-gray-400">
                {isEnglish ?
                    "REST API for getting pokemon information using ASP.NET Core, Entity Framework Core and Sqlite." :
                    "API REST para obtener información de pokemones. Usandp ASP.NET Core, Entity Framework COre y Slito."
                  }
                </p><br/>
                <h4 className="pt-4 text-teal-600">#ASP.NET #C# #EFCore #Sqlite</h4>
              </div>
            </a>

          </div>
        </section>
        
        <br/>
      </main>
    </div>
  )
}
